steps:
  # Build the container image using Cloud Native Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args: 
      - 'build'
      - '--network'
      - 'cloudbuild'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '.'
      - '--env'
      - 'NODE_ENV=production'
      - '--env'
      - 'NEXT_TELEMETRY_DISABLED=1'
      - '--env'
      - 'NPM_CONFIG_PRODUCTION=false'
      - '--env'
      - 'NPM_CONFIG_INCLUDE=dev'
      - '--buildpack'
      - 'gcr.io/buildpacks/builder:latest'
    dir: 'frontend'
    env:
      - 'NODE_ENV=production'
      - 'NEXT_TELEMETRY_DISABLED=1'
      - 'NPM_CONFIG_PRODUCTION=false'
      - 'NPM_CONFIG_INCLUDE=dev'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--max-instances'
      - '20'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '1000'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
